apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cireleasechecklist-ingress
  namespace: devops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cireleasechecklist.arconnet.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cireleasechecklist-service
                port:
                  number: 80
