apiVersion: v1
kind: Service
metadata:
  name: cireleasechecklist-service
  namespace: devops
spec:
  selector:
    app: cireleasechecklist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8020
      name: http
  type: ClusterIP